environment:
  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python33

install:
  - ps: Install-Product node ''
  - scripts\install.cmd %PYTHON%

test_script:
  - scripts\run_tests.cmd %PYTHON%

build: off
version: "{build}"
clone_depth: 3
max_jobs: 2
